
POST http://localhost:3001/v1/ticket
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1laHVsb3N3YWwyMUBnbWFpbC5jb20iLCJpYXQiOjE2MjM3NjQzNTMsImV4cCI6MTYyMzc2NTI1M30.sutJrZ0eoD6cwF4X7rLXHjVfKFxD628Skwgf6vC1G_Q

{
    "subject": "Form Issue",
    "sender": "XYZ",
    "message": "Contact form not working. Please fix as soon as possible"
}

###Get all tickets for a user
GET http://localhost:3001/v1/ticket
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1laHVsb3N3YWwyMUBnbWFpbC5jb20iLCJpYXQiOjE2MjM3Njg4NzcsImV4cCI6MTYyMzc2OTc3N30.6V9RVgw6JlFXeIA1JOaWj5ln4PdBNp0o_rwSqsj-078