
### User signup endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "Sangeeta Jitendra Oswal",
    "company":"Home",
    "address":"Pune",
    "phone":1234567890,
    "email":"sangeetaoswal28@gmail.com",
    "password":"1234567890"
}
### User signin endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email":"mehuloswal21@gmail.com",
    "password":"password3"
}
### Get a user profile endpoint
GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1laHVsb3N3YWwyMUBnbWFpbC5jb20iLCJpYXQiOjE2MjM2NTU2MTIsImV4cCI6MTYyMzY1NjUxMn0.EuQw7ux2NsXGbk8iTOCO_qRPW2SYsALoiJVNe-Ksswg


###Tokens Router

###Get refreshed token 
GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoibWVodWxvc3dhbDIxQGdtYWlsLmNvbSIsImlhdCI6MTYyMzY1OTEzMiwiZXhwIjoxNjI2MjUxMTMyfQ.-XRbv8tZTpnA5TlAqFDX9jHDwnyShgAkVEyV5v5FKj8


###Reset Password
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email":"mehuloswal21@gmail.com"
}

###Update new Password endpoint

PATCH http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email":"mehuloswal21@gmail.com",
    "pin" : 979176112, 
    "newPassword":"password6"
}